### ISSUE TITLE
AsyncTCPSock vs AsyncTCP

### ISSUE THREAD

**Issue by guilhermeaiolfi** [yubox-node-org/AsyncTCPSock#7]
Hi,

I am trying to understand how all those pieces in the ESP32 world fit together (I've got one ESP32 a couple of days ago). I played one day in the arduino IDE and now I'm using the PlatformIO and Arduino Core there. I was going to use AsyncTCP and ESPAsyncWebServer but some comments made me look for forks as the stability in the original project is not that great. Hopefully you can put answer some of my questions:

1) Is this a replacement for AsyncTCP? Can I use in my environment? Or do I need esp-idf (that's something I don't really know exactly what it is).
2) Your ESPAsyncWebServer are suppose to work with AsyncTCP or AsyncTCPSock? or Both?
3) What is the advantage of using AsyncTCPSock?

Thanks

**Comment by DRSDavidSoft** [comment]
Excellent information, I was wondering about the differences since there is no `README.md` files.  Additionally, if #23 could be addressed, if would be beneficial to new users discovering the repo and using it!

**Comment by mathieucarbou** [comment]
Besides #23, you can also see some perf tests I did on ESPAsyncWS comparing the 2 libraries on te community maintained fork of https://github.com/mathieucarbou/ESPAsyncWebServer?tab=readme-ov-file#performance:

https://github.com/mathieucarbou/ESPAsyncWebServer?tab=readme-ov-file#performance
